In [2]:
import numpy as np
import pandas as pd
import scipy as stats

In [3]:
a=np.array([10,20,30,40,np.nan])

In [4]:
a

array([10., 20., 30., 40., nan])

In [5]:
np.nan_to_num(a)

array([10., 20., 30., 40.,  0.])

In [6]:
np.nanmean(a)

25.0

In [10]:
np.nanargmax(a)

3

In [12]:
np.nanmax(a)

40.0

In [13]:
np.argmin(a)

4

In [14]:
np.nanargmax(a)

3

In [16]:
np.nanargmin(a)

0

In [18]:
np.nanmean(a)

25.0

In [19]:
np.nanmedian(a)

25.0

In [20]:
np.nancumprod(a)

array([1.0e+01, 2.0e+02, 6.0e+03, 2.4e+05, 2.4e+05])

In [21]:
np.nancumsum(a)

array([ 10.,  30.,  60., 100., 100.])

In [26]:
np.nan_to_num(a)

array([10., 20., 30., 40.,  0.])

In [28]:
np.nansum(a)

100.0