In [1]:
import numpy as np
import pandas as pd
import pandas_profiling 
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
pd.__version__

'1.0.1'

In [3]:
np.__version__

'1.18.1'

In [4]:
pandas_profiling.__version__

'2.4.0'

In [10]:
ind=[('california',2000),('california',2010),('new york',2000),('newyork',2010),('texas',2000),('texas',2010)]
population=[33871648,37253956,18976457,19378102,208551820,25145561]

In [37]:
ind.pop

<function list.pop>

In [38]:
pop.index

NameError: name 'pop' is not defined

In [12]:
population

[33871648, 37253956, 18976457, 19378102, 208551820, 25145561]

In [16]:
pop[[i for i in pop.index if i[1]]==2010]

NameError: name 'pop' is not defined

In [14]:
for i in pop.index:
    if i[1]==2010:
        print(i,pop[i])

NameError: name 'pop' is not defined

In [18]:
#better way to designing the indexing

In [19]:
pop.index

NameError: name 'pop' is not defined

In [21]:
pop_df=pd.DataFrame({'Total':pop,'under18':[9267089,9284094,4687374,4318033,5906301,6879014]})

NameError: name 'pop' is not defined

In [24]:
df=pd.DataFrame(np.random.rand(4,2),index=[['a','b','a','b'],[1,2,1,2]],columns=['data1','data2'])

In [25]:
df

data1     data2
a 1  0.591464  0.267527
b 2  0.087724  0.070773
a 1  0.659747  0.199927
b 2  0.411181  0.962186

In [26]:
df=pd.DataFrame(np.random.rand(4,2),index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])

In [27]:
df

data1     data2
a 1  0.220764  0.702175
  2  0.182295  0.287292
b 1  0.161334  0.335136
  2  0.683350  0.207018

In [31]:
data=({('california',2000):33871648,('california':2010):37253956,('texas',2000):20851820,('texas',2010):241455561,('newyork',2000):18976457,
      ('newyork',2010):19378102})
pd.series(data)

SyntaxError: invalid syntax (<ipython-input-31-cfa32e749113>, line 1)

In [32]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [33]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [34]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [35]:
pd.MultiIndex(levels=[['a','b'],[1,2]],codes=[[0,0,1,1],[0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [36]:
pop.index.names=['state','year']
pop

NameError: name 'pop' is not defined

In [39]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2,3]],names=['year','visit'])
columns=pd.MultiIndex.from_product([['rani','raju','sam'],['BMI','Temp','Weight']],names=['Name','type'])

In [41]:
data=np.round(np.random.randn(6,9),2)

In [42]:
data

array([[ 0.72, -0.36,  1.54, -1.19, -0.45, -0.69,  1.05, -1.5 ,  0.7 ],
       [-0.84,  1.28,  0.35,  0.09, -0.37, -1.14, -2.8 ,  1.3 , -1.53],
       [-0.52,  0.05, -0.21,  2.44,  1.89,  0.62, -0.97,  0.7 ,  0.21],
       [-1.12,  0.56,  1.54, -0.62,  2.03,  1.25,  0.13,  0.25, -0.55],
       [ 1.42,  0.15, -1.05,  0.17, -2.61,  0.73,  1.84,  0.26,  0.28],
       [-0.29, -0.6 ,  0.98,  0.33, -0.39, -1.08,  0.51,  0.77, -0.28]])

In [44]:
data[:,::2]*=10
data

array([[  7.2 ,  -0.36,  15.4 ,  -1.19,  -4.5 ,  -0.69,  10.5 ,  -1.5 ,
          7.  ],
       [ -8.4 ,   1.28,   3.5 ,   0.09,  -3.7 ,  -1.14, -28.  ,   1.3 ,
        -15.3 ],
       [ -5.2 ,   0.05,  -2.1 ,   2.44,  18.9 ,   0.62,  -9.7 ,   0.7 ,
          2.1 ],
       [-11.2 ,   0.56,  15.4 ,  -0.62,  20.3 ,   1.25,   1.3 ,   0.25,
         -5.5 ],
       [ 14.2 ,   0.15, -10.5 ,   0.17, -26.1 ,   0.73,  18.4 ,   0.26,
          2.8 ],
       [ -2.9 ,  -0.6 ,   9.8 ,   0.33,  -3.9 ,  -1.08,   5.1 ,   0.77,
         -2.8 ]])

In [45]:
data+=37

In [46]:
data

array([[44.2 , 36.64, 52.4 , 35.81, 32.5 , 36.31, 47.5 , 35.5 , 44.  ],
       [28.6 , 38.28, 40.5 , 37.09, 33.3 , 35.86,  9.  , 38.3 , 21.7 ],
       [31.8 , 37.05, 34.9 , 39.44, 55.9 , 37.62, 27.3 , 37.7 , 39.1 ],
       [25.8 , 37.56, 52.4 , 36.38, 57.3 , 38.25, 38.3 , 37.25, 31.5 ],
       [51.2 , 37.15, 26.5 , 37.17, 10.9 , 37.73, 55.4 , 37.26, 39.8 ],
       [34.1 , 36.4 , 46.8 , 37.33, 33.1 , 35.92, 42.1 , 37.77, 34.2 ]])

In [47]:
health_data=pd.DataFrame(data,index=index,columns=columns)
health_data

Name        rani                 raju                sam              
type         BMI   Temp Weight    BMI  Temp Weight   BMI   Temp Weight
year visit                                                            
2013 1      44.2  36.64   52.4  35.81  32.5  36.31  47.5  35.50   44.0
     2      28.6  38.28   40.5  37.09  33.3  35.86   9.0  38.30   21.7
     3      31.8  37.05   34.9  39.44  55.9  37.62  27.3  37.70   39.1
2014 1      25.8  37.56   52.4  36.38  57.3  38.25  38.3  37.25   31.5
     2      51.2  37.15   26.5  37.17  10.9  37.73  55.4  37.26   39.8
     3      34.1  36.40   46.8  37.33  33.1  35.92  42.1  37.77   34.2

In [48]:
health_data.to_csv('filename')

In [49]:
health_data['raju']

type          BMI  Temp  Weight
year visit                     
2013 1      35.81  32.5   36.31
     2      37.09  33.3   35.86
     3      39.44  55.9   37.62
2014 1      36.38  57.3   38.25
     2      37.17  10.9   37.73
     3      37.33  33.1   35.92

In [52]:
health_data.iloc[1]

Name  type  
rani  BMI       28.60
      Temp      38.28
      Weight    40.50
raju  BMI       37.09
      Temp      33.30
      Weight    35.86
sam   BMI        9.00
      Temp      38.30
      Weight    21.70
Name: (2013, 2), dtype: float64

In [54]:
health_data.iloc[0:4]

Name        rani                 raju                sam              
type         BMI   Temp Weight    BMI  Temp Weight   BMI   Temp Weight
year visit                                                            
2013 1      44.2  36.64   52.4  35.81  32.5  36.31  47.5  35.50   44.0
     2      28.6  38.28   40.5  37.09  33.3  35.86   9.0  38.30   21.7
     3      31.8  37.05   34.9  39.44  55.9  37.62  27.3  37.70   39.1
2014 1      25.8  37.56   52.4  36.38  57.3  38.25  38.3  37.25   31.5