In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1=np.array([1,None,3,4])

In [3]:
vals1

array([1, None, 3, 4], dtype=object)

In [4]:
vals1.dtype


dtype('O')

In [5]:
v=np.arange(12).reshape(3,4)
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
v.dtype

dtype('int64')

In [7]:
v[0][0]

0

In [8]:
v[0][0]='None'

ValueError: invalid literal for int() with base 10: 'None'

In [9]:
try:
    a='hello2'
    print(int(a))
except NameError as ne:
    print(ne)

ValueError: invalid literal for int() with base 10: 'hello2'

In [11]:
np.arange(1E6)

array([0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 9.99997e+05,
       9.99998e+05, 9.99999e+05])

In [13]:
for dtype in ['object','int','float','complex']:
    print('dtype=',dtype)
    %time np.arange(1E6,dtype=dtype).sum()
    print()

dtype= object
CPU times: user 53.5 ms, sys: 7.67 ms, total: 61.1 ms
Wall time: 60.4 ms

dtype= int
CPU times: user 65 µs, sys: 4.2 ms, total: 4.26 ms
Wall time: 2.95 ms

dtype= float
CPU times: user 2.18 ms, sys: 308 µs, total: 2.49 ms
Wall time: 1.82 ms

dtype= complex
CPU times: user 6.39 ms, sys: 0 ns, total: 6.39 ms
Wall time: 5.93 ms



In [14]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [15]:
vals1.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [16]:
vals1+10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [17]:
vals2=np.array([1,3,4,np.nan])
vals2.dtype

dtype('float64')

In [18]:
1+np.nan

nan

In [19]:
0*np.nan

nan

In [21]:
vals2.sum(),vals2.min(),vals2.mean(),vals2.max()

(nan, nan, nan, nan)

In [25]:
import pandas as pd
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [26]:
x=pd.Series(range(4),dtype=int)
x

0    0
1    1
2    2
3    3
dtype: int64

In [27]:
x[3]=None

In [28]:
x

0    0.0
1    1.0
2    2.0
3    NaN
dtype: float64

In [29]:
x.add(2)

0    2.0
1    3.0
2    4.0
3    NaN
dtype: float64

In [31]:
np.nan_to_num(x)

array([0., 1., 2., 0.])

In [32]:
np.max(x)

2.0

In [33]:
np.min(x)

0.0

In [34]:
np.nanmean(x),np.nanmedian(x)

(1.0, 1.0)

In [35]:
data=pd.Series([10,20,30,np.nan,None])

In [36]:
data

0    10.0
1    20.0
2    30.0
3     NaN
4     NaN
dtype: float64

In [37]:
data.isnull()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [38]:
data.notnull()

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [39]:
data.isnull()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [40]:
data.notna()

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [43]:
df=pd.DataFrame([[1,np.nan,2,None],[2,3,4,10],[np.nan,4,9,155]])

In [44]:
df

0    1  2      3
0  1.0  NaN  2    NaN
1  2.0  3.0  4   10.0
2  NaN  4.0  9  155.0

In [45]:
df.dropna()

0    1  2     3
1  2.0  3.0  4  10.0

In [46]:
df

0    1  2      3
0  1.0  NaN  2    NaN
1  2.0  3.0  4   10.0
2  NaN  4.0  9  155.0