In [1]:
letters=['c','h','e','c','k','i','o']
letters

['c', 'h', 'e', 'c', 'k', 'i', 'o']

In [2]:
letters[6]

'o'

In [3]:
letters[0:5]

['c', 'h', 'e', 'c', 'k']

In [4]:
letters[0]='m'
letters

['m', 'h', 'e', 'c', 'k', 'i', 'o']

In [5]:
letters[1:4:2]

['h', 'c']

In [6]:
letters

['m', 'h', 'e', 'c', 'k', 'i', 'o']

In [8]:
#numpy
import numpy as np
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [12]:

list1 = [1, 2, 3, 4 ,5, 6] 
list2 = [10, 9, 8, 7, 6, 5] 
  
# Multiplying both lists directly would give an error. 
print(list1*list2) 

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
import numpy as np 
  
list1 = [1, 2, 3, 4, 5, 6] 
list2 = [10, 9, 8, 7, 6, 5] 
  
# Convert list1 into a NumPy array 
a1 = np.array(list1) 
  
# Convert list2 into a NumPy array 
a2 = np.array(list2) 
  
print(a1*a2) 

[10 18 24 28 30 30]


In [21]:
# Create a sequence of integers from 10 to 1 with a step of -2 
a = np.arange(1, 20, 3)  
print("\n A sequential array with a positive step: \n",a) 
  


 A sequential array with a positive step: 
 [ 1  4  7 10 13 16 19]


In [22]:
  
# Indexes are specified inside the np.array method. 
newarr = a[np.array([3, 1, 2 ])] 
print("\n Elements at these indices are:\n",newarr) 


 Elements at these indices are:
 [10  4  7]


In [23]:
import numpy as np 
# NumPy array with elements from 1 to 9 
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
# Index values can be negative. 
arr = x[np.array([1, 3, -3])] 
print("\n Elements are : \n",arr) 


 Elements are : 
 [2 4 7]


In [25]:
# Python program for basic slicing. 
import numpy as np 
  
# Arrange elements from 0 to 19 
a = np.arange(20) 
print("\n Array is:\n ",a) 
  
# a[start:stop:step] 
print("\n a[-8:17:1]  = ",a[-8:17])  
  
# The : operator means all elements till the end. 
print("\n a[10:]  = ",a[10:]) 



 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [26]:
a[-12:15]

array([ 8,  9, 10, 11, 12, 13, 14])

In [27]:
a[-12:15:2]

array([ 8, 10, 12, 14])

In [29]:
a[-12:15:3]

array([ 8, 11, 14])

In [30]:
a[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [32]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
a[:-5]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
# A 3 dimensional array. 
b = np.array([[[1, 2, 3],[4, 5, 6]], 
              [[7, 8, 9],[10, 11, 12]]]) 

In [37]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
b[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

In [43]:
b[1:2]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
print(a[[0 ,1 ,2 ],[0 ,0 ,1]]) 

[1 3 6]


In [47]:
a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50]) 

[ 80 100]


In [58]:
import numpy as np
# A 3-Dimensional array
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [59]:
# slicing and indexing
print("\n a[0, 3:5] = ",a[0, 3:5]) 




 a[0, 3:5] =  [3 4]


In [62]:
a[1,2:5]

array([ 8,  9, 10])

In [61]:
a[4,2:5]

array([26, 27, 28])

In [63]:
print("\n a[4:, 4:] = ",a[4:, 4:]) 



 a[4:, 4:] =  [[28 29]
 [34 35]]


In [65]:
a[2:,4:]

array([[16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])

In [72]:
a[2::2,::2]# this is called  step

array([[12, 14, 16],
       [24, 26, 28]])

In [69]:
a[:,2]# this is only 2 row elements values

array([ 2,  8, 14, 20, 26, 32])

In [70]:
a[:,4]

array([ 4, 10, 16, 22, 28, 34])